CREATE INDEX "idx_anime_id_mal" ON "anime" ("id_mal");--> statement-breakpoint
CREATE INDEX "idx_anime_status" ON "anime" ("status");--> statement-breakpoint
CREATE INDEX "idx_anime_type" ON "anime" ("type");--> statement-breakpoint
CREATE INDEX "idx_anime_format" ON "anime" ("format");--> statement-breakpoint
CREATE INDEX "idx_anime_season" ON "anime" ("season");--> statement-breakpoint
CREATE INDEX "idx_anime_season_year" ON "anime" ("season_year");--> statement-breakpoint
CREATE INDEX "idx_anime_source" ON "anime" ("source");--> statement-breakpoint
CREATE INDEX "idx_anime_country" ON "anime" ("country");--> statement-breakpoint
CREATE INDEX "idx_anime_is_adult" ON "anime" ("is_adult");--> statement-breakpoint
CREATE INDEX "idx_anime_is_licensed" ON "anime" ("is_licensed");--> statement-breakpoint
CREATE INDEX "idx_anime_score" ON "anime" ("score");--> statement-breakpoint
CREATE INDEX "idx_anime_popularity" ON "anime" ("popularity");--> statement-breakpoint
CREATE INDEX "idx_anime_trending" ON "anime" ("trending");--> statement-breakpoint
CREATE INDEX "idx_anime_favorites" ON "anime" ("favorites");--> statement-breakpoint
CREATE INDEX "idx_anime_franchise" ON "anime" ("franchise");--> statement-breakpoint
CREATE INDEX "idx_anime_next_airing_episode" ON "anime" ("next_airing_episode");--> statement-breakpoint
CREATE INDEX "idx_anime_updated_at" ON "anime" ("updated_at");--> statement-breakpoint
CREATE INDEX "idx_anime_season_season_year" ON "anime" ("season","season_year");--> statement-breakpoint
CREATE INDEX "idx_anime_season_year_format" ON "anime" ("season_year","format");--> statement-breakpoint
CREATE INDEX "idx_anime_character_image_character_id" ON "anime_character_image" ("character_id");--> statement-breakpoint
CREATE INDEX "idx_anime_character_name_character_id" ON "anime_character_name" ("character_id");--> statement-breakpoint
CREATE INDEX "idx_anime_chronology_parent_id" ON "anime_chronology" ("parent_id");--> statement-breakpoint
CREATE INDEX "idx_anime_chronology_anime_id" ON "anime_chronology" ("anime_id");--> statement-breakpoint
CREATE INDEX "idx_anime_chronology_related_id" ON "anime_chronology" ("related_id");--> statement-breakpoint
CREATE INDEX "idx_anime_end_date_anime_id" ON "anime_end_date" ("anime_id");--> statement-breakpoint
CREATE INDEX "idx_anime_end_date_year" ON "anime_end_date" ("year");--> statement-breakpoint
CREATE INDEX "idx_anime_poster_anime_id" ON "anime_poster" ("anime_id");--> statement-breakpoint
CREATE INDEX "idx_anime_recommendation_parent_id" ON "anime_recommendation" ("parent_id");--> statement-breakpoint
CREATE INDEX "idx_anime_recommendation_anime_id" ON "anime_recommendation" ("anime_id");--> statement-breakpoint
CREATE INDEX "idx_anime_recommendation_related_id" ON "anime_recommendation" ("related_id");--> statement-breakpoint
CREATE INDEX "idx_anime_score_distribution_anime_id" ON "anime_score_distribution" ("anime_id");--> statement-breakpoint
CREATE INDEX "idx_anime_start_date_anime_id" ON "anime_start_date" ("anime_id");--> statement-breakpoint
CREATE INDEX "idx_anime_start_date_year" ON "anime_start_date" ("year");--> statement-breakpoint
CREATE INDEX "idx_anime_status_distribution_anime_id" ON "anime_status_distribution" ("anime_id");--> statement-breakpoint
CREATE INDEX "idx_anime_tag_category" ON "anime_tag" ("category");--> statement-breakpoint
CREATE INDEX "idx_anime_tag_is_adult" ON "anime_tag" ("is_adult");--> statement-breakpoint
CREATE INDEX "idx_anime_title_anime_id" ON "anime_title" ("anime_id");--> statement-breakpoint
CREATE INDEX "idx_anime_to_airing_schedule_a" ON "_anime_to_airing_schedule" ("A");--> statement-breakpoint
CREATE INDEX "idx_anime_to_artwork_a" ON "_anime_to_artwork" ("A");--> statement-breakpoint
CREATE INDEX "idx_anime_to_character_anime_id" ON "_anime_to_character" ("anime_id");--> statement-breakpoint
CREATE INDEX "idx_anime_to_character_character_id" ON "_anime_to_character" ("character_id");--> statement-breakpoint
CREATE INDEX "idx_anime_to_genre_a" ON "_anime_to_genre" ("A");--> statement-breakpoint
CREATE INDEX "idx_anime_to_genre_b" ON "_anime_to_genre" ("B");--> statement-breakpoint
CREATE INDEX "idx_anime_to_image_a" ON "_anime_to_image" ("A");--> statement-breakpoint
CREATE INDEX "idx_anime_to_link_a" ON "_anime_to_link" ("A");--> statement-breakpoint
CREATE INDEX "idx_anime_to_other_description_a" ON "_anime_to_other_description" ("A");--> statement-breakpoint
CREATE INDEX "idx_anime_to_other_title_a" ON "_anime_to_other_title" ("A");--> statement-breakpoint
CREATE INDEX "idx_anime_to_screenshot_a" ON "_anime_to_screenshot" ("A");--> statement-breakpoint
CREATE INDEX "idx_anime_to_studio_anime_id" ON "_anime_to_studio" ("anime_id");--> statement-breakpoint
CREATE INDEX "idx_anime_to_studio_studio_id" ON "_anime_to_studio" ("studio_id");--> statement-breakpoint
CREATE INDEX "idx_anime_to_tag_anime_id" ON "_anime_to_tag" ("anime_id");--> statement-breakpoint
CREATE INDEX "idx_anime_to_tag_tag_id" ON "_anime_to_tag" ("tag_id");--> statement-breakpoint
CREATE INDEX "idx_anime_to_video_a" ON "_anime_to_video" ("A");--> statement-breakpoint
CREATE INDEX "idx_anime_voice_image_voice_actor_id" ON "anime_voice_image" ("voice_actor_id");--> statement-breakpoint
CREATE INDEX "idx_anime_voice_name_voice_actor_id" ON "anime_voice_name" ("voice_actor_id");--> statement-breakpoint
CREATE INDEX "idx_character_to_voice_actor_a" ON "_character_to_voice_actor" ("A");--> statement-breakpoint
CREATE INDEX "idx_character_to_voice_actor_b" ON "_character_to_voice_actor" ("B");