export enum UpdateType {
  ANIWATCH = 'ANIWATCH',
  ANIMEKAI = 'ANIMEKAI',
  ANIMEPAHE = 'ANIMEPAHE',
  ANILIST = 'ANILIST',
  ANILIBRIA = 'ANILIBRIA',
  SHIKIMORI = 'SHIKIMORI',
  TMDB = 'TMDB',
  TVDB = 'TVDB',
  KITSU = 'KITSU',
  ANIZIP = 'ANIZIP',
}
