ALTER TABLE "anime" ALTER COLUMN "background" SET DATA TYPE text USING "background"::text;--> statement-breakpoint
ALTER TABLE "anime_artwork" ALTER COLUMN "url" SET DATA TYPE text USING "url"::text;--> statement-breakpoint
ALTER TABLE "anime_artwork" ALTER COLUMN "large" SET DATA TYPE text USING "large"::text;--> statement-breakpoint
ALTER TABLE "anime_artwork" ALTER COLUMN "medium" SET DATA TYPE text USING "medium"::text;--> statement-breakpoint
ALTER TABLE "anime_character_image" ALTER COLUMN "large" SET DATA TYPE text USING "large"::text;--> statement-breakpoint
ALTER TABLE "anime_character_image" ALTER COLUMN "medium" SET DATA TYPE text USING "medium"::text;--> statement-breakpoint
ALTER TABLE "anime_character_name" ALTER COLUMN "first" SET DATA TYPE text USING "first"::text;--> statement-breakpoint
ALTER TABLE "anime_character_name" ALTER COLUMN "middle" SET DATA TYPE text USING "middle"::text;--> statement-breakpoint
ALTER TABLE "anime_character_name" ALTER COLUMN "last" SET DATA TYPE text USING "last"::text;--> statement-breakpoint
ALTER TABLE "anime_character_name" ALTER COLUMN "full" SET DATA TYPE text USING "full"::text;--> statement-breakpoint
ALTER TABLE "anime_character_name" ALTER COLUMN "native" SET DATA TYPE text USING "native"::text;--> statement-breakpoint
ALTER TABLE "anime_episode" ALTER COLUMN "title" SET DATA TYPE text USING "title"::text;--> statement-breakpoint
ALTER TABLE "anime_episode_image" ALTER COLUMN "small" SET DATA TYPE text USING "small"::text;--> statement-breakpoint
ALTER TABLE "anime_episode_image" ALTER COLUMN "medium" SET DATA TYPE text USING "medium"::text;--> statement-breakpoint
ALTER TABLE "anime_episode_image" ALTER COLUMN "large" SET DATA TYPE text USING "large"::text;--> statement-breakpoint
ALTER TABLE "anime_image" ALTER COLUMN "url" SET DATA TYPE text USING "url"::text;--> statement-breakpoint
ALTER TABLE "anime_image" ALTER COLUMN "small" SET DATA TYPE text USING "small"::text;--> statement-breakpoint
ALTER TABLE "anime_image" ALTER COLUMN "medium" SET DATA TYPE text USING "medium"::text;--> statement-breakpoint
ALTER TABLE "anime_image" ALTER COLUMN "large" SET DATA TYPE text USING "large"::text;--> statement-breakpoint
ALTER TABLE "anime_link" ALTER COLUMN "link" SET DATA TYPE text USING "link"::text;--> statement-breakpoint
ALTER TABLE "anime_link" ALTER COLUMN "label" SET DATA TYPE text USING "label"::text;--> statement-breakpoint
ALTER TABLE "anime_other_title" ALTER COLUMN "title" SET DATA TYPE text USING "title"::text;--> statement-breakpoint
ALTER TABLE "anime_poster" ALTER COLUMN "small" SET DATA TYPE text USING "small"::text;--> statement-breakpoint
ALTER TABLE "anime_poster" ALTER COLUMN "medium" SET DATA TYPE text USING "medium"::text;--> statement-breakpoint
ALTER TABLE "anime_poster" ALTER COLUMN "large" SET DATA TYPE text USING "large"::text;--> statement-breakpoint
ALTER TABLE "anime_screenshot" ALTER COLUMN "url" SET DATA TYPE text USING "url"::text;--> statement-breakpoint
ALTER TABLE "anime_screenshot" ALTER COLUMN "small" SET DATA TYPE text USING "small"::text;--> statement-breakpoint
ALTER TABLE "anime_screenshot" ALTER COLUMN "medium" SET DATA TYPE text USING "medium"::text;--> statement-breakpoint
ALTER TABLE "anime_screenshot" ALTER COLUMN "large" SET DATA TYPE text USING "large"::text;--> statement-breakpoint
ALTER TABLE "anime_studio" ALTER COLUMN "name" SET DATA TYPE text USING "name"::text;--> statement-breakpoint
ALTER TABLE "anime_title" ALTER COLUMN "romaji" SET DATA TYPE text USING "romaji"::text;--> statement-breakpoint
ALTER TABLE "anime_title" ALTER COLUMN "english" SET DATA TYPE text USING "english"::text;--> statement-breakpoint
ALTER TABLE "anime_title" ALTER COLUMN "native" SET DATA TYPE text USING "native"::text;--> statement-breakpoint
ALTER TABLE "anime_video" ALTER COLUMN "url" SET DATA TYPE text USING "url"::text;--> statement-breakpoint
ALTER TABLE "anime_video" ALTER COLUMN "title" SET DATA TYPE text USING "title"::text;--> statement-breakpoint
ALTER TABLE "anime_video" ALTER COLUMN "thumbnail" SET DATA TYPE text USING "thumbnail"::text;--> statement-breakpoint
ALTER TABLE "anime_video" ALTER COLUMN "artist" SET DATA TYPE text USING "artist"::text;--> statement-breakpoint
ALTER TABLE "anime_voice_actor" ALTER COLUMN "home_town" SET DATA TYPE text USING "home_town"::text;--> statement-breakpoint
ALTER TABLE "anime_voice_image" ALTER COLUMN "large" SET DATA TYPE text USING "large"::text;--> statement-breakpoint
ALTER TABLE "anime_voice_image" ALTER COLUMN "medium" SET DATA TYPE text USING "medium"::text;--> statement-breakpoint
ALTER TABLE "anime_voice_name" ALTER COLUMN "first" SET DATA TYPE text USING "first"::text;--> statement-breakpoint
ALTER TABLE "anime_voice_name" ALTER COLUMN "middle" SET DATA TYPE text USING "middle"::text;--> statement-breakpoint
ALTER TABLE "anime_voice_name" ALTER COLUMN "last" SET DATA TYPE text USING "last"::text;--> statement-breakpoint
ALTER TABLE "anime_voice_name" ALTER COLUMN "full" SET DATA TYPE text USING "full"::text;--> statement-breakpoint
ALTER TABLE "anime_voice_name" ALTER COLUMN "native" SET DATA TYPE text USING "native"::text;