ALTER TABLE "media" ADD COLUMN "local_score" real DEFAULT 0;--> statement-breakpoint
ALTER TABLE "media" ALTER COLUMN "status" SET DATA TYPE text USING "status"::text;--> statement-breakpoint
ALTER TABLE "media" ALTER COLUMN "type" SET DATA TYPE text USING "type"::text;--> statement-breakpoint
ALTER TABLE "media" ALTER COLUMN "format" SET DATA TYPE text USING "format"::text;--> statement-breakpoint
ALTER TABLE "media" ALTER COLUMN "season" SET DATA TYPE text USING "season"::text;--> statement-breakpoint
ALTER TABLE "media" ALTER COLUMN "country" SET DATA TYPE text USING "country"::text;--> statement-breakpoint
ALTER TABLE "media" ALTER COLUMN "source" SET DATA TYPE text USING "source"::text;--> statement-breakpoint
ALTER TABLE "media" ALTER COLUMN "hashtag" SET DATA TYPE text USING "hashtag"::text;--> statement-breakpoint
ALTER TABLE "media" ALTER COLUMN "local_favorites" SET DEFAULT 0;--> statement-breakpoint
ALTER TABLE "media" ALTER COLUMN "color" SET DATA TYPE text USING "color"::text;--> statement-breakpoint
ALTER TABLE "media" ALTER COLUMN "franchise" SET DATA TYPE text USING "franchise"::text;--> statement-breakpoint
ALTER TABLE "media_age_rating" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_age_rating" ALTER COLUMN "rating" SET DATA TYPE text USING "rating"::text;--> statement-breakpoint
ALTER TABLE "media_age_rating" ALTER COLUMN "description" SET DATA TYPE text USING "description"::text;--> statement-breakpoint
ALTER TABLE "media_airing_schedule" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_alt_description" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_alt_description" ALTER COLUMN "source" SET DATA TYPE text USING "source"::text;--> statement-breakpoint
ALTER TABLE "media_alt_description" ALTER COLUMN "language" SET DATA TYPE text USING "language"::text;--> statement-breakpoint
ALTER TABLE "media_alt_title" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_alt_title" ALTER COLUMN "source" SET DATA TYPE text USING "source"::text;--> statement-breakpoint
ALTER TABLE "media_alt_title" ALTER COLUMN "language" SET DATA TYPE text USING "language"::text;--> statement-breakpoint
ALTER TABLE "media_artwork" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_artwork" ALTER COLUMN "iso_639_1" SET DATA TYPE text USING "iso_639_1"::text;--> statement-breakpoint
ALTER TABLE "media_artwork" ALTER COLUMN "type" SET DATA TYPE text USING "type"::text;--> statement-breakpoint
ALTER TABLE "media_artwork" ALTER COLUMN "source" SET DATA TYPE text USING "source"::text;--> statement-breakpoint
ALTER TABLE "media_broadcast" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_broadcast" ALTER COLUMN "time" SET DATA TYPE text USING "time"::text;--> statement-breakpoint
ALTER TABLE "media_broadcast" ALTER COLUMN "timezone" SET DATA TYPE text USING "timezone"::text;--> statement-breakpoint
ALTER TABLE "media_character" ALTER COLUMN "age" SET DATA TYPE text USING "age"::text;--> statement-breakpoint
ALTER TABLE "media_character" ALTER COLUMN "blood_type" SET DATA TYPE text USING "blood_type"::text;--> statement-breakpoint
ALTER TABLE "media_character" ALTER COLUMN "gender" SET DATA TYPE text USING "gender"::text;--> statement-breakpoint
ALTER TABLE "media_character_birth_date" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_character_image" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_character_name" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_chronology" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_embedding" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_end_date" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_episode" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_episode" ALTER COLUMN "air_date" SET DATA TYPE text USING "air_date"::text;--> statement-breakpoint
ALTER TABLE "media_episode_image" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_episode_image" ALTER COLUMN "episode_id" SET DATA TYPE text USING "episode_id"::text;--> statement-breakpoint
ALTER TABLE "media_genre" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_genre" ALTER COLUMN "name" SET DATA TYPE text USING "name"::text;--> statement-breakpoint
ALTER TABLE "media_image" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_image" ALTER COLUMN "type" SET DATA TYPE text USING "type"::text;--> statement-breakpoint
ALTER TABLE "media_image" ALTER COLUMN "source" SET DATA TYPE text USING "source"::text;--> statement-breakpoint
ALTER TABLE "media_last_airing_episode" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_latest_airing_episode" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_link" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_link" ALTER COLUMN "type" SET DATA TYPE text USING "type"::text;--> statement-breakpoint
ALTER TABLE "media_local_score_distribution" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_local_status_distribution" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_next_airing_episode" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_poster" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_recommendation" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_relation" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_relation" ALTER COLUMN "relation_type" SET DATA TYPE text USING "relation_type"::text;--> statement-breakpoint
ALTER TABLE "media_score_distribution" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_screenshot" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_screenshot" ALTER COLUMN "source" SET DATA TYPE text USING "source"::text;--> statement-breakpoint
ALTER TABLE "media_start_date" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_statistic" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_status_distribution" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_status_distribution" ALTER COLUMN "status" SET DATA TYPE text USING "status"::text;--> statement-breakpoint
ALTER TABLE "media_tag" ALTER COLUMN "name" SET DATA TYPE text USING "name"::text;--> statement-breakpoint
ALTER TABLE "media_tag" ALTER COLUMN "category" SET DATA TYPE text USING "category"::text;--> statement-breakpoint
ALTER TABLE "media_title" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "_media_to_alt_description" ALTER COLUMN "B" SET DATA TYPE text USING "B"::text;--> statement-breakpoint
ALTER TABLE "_media_to_alt_title" ALTER COLUMN "B" SET DATA TYPE text USING "B"::text;--> statement-breakpoint
ALTER TABLE "_media_to_artwork" ALTER COLUMN "B" SET DATA TYPE text USING "B"::text;--> statement-breakpoint
ALTER TABLE "_media_to_character" ALTER COLUMN "role" SET DATA TYPE text USING "role"::text;--> statement-breakpoint
ALTER TABLE "_media_to_genre" ALTER COLUMN "B" SET DATA TYPE text USING "B"::text;--> statement-breakpoint
ALTER TABLE "_media_to_image" ALTER COLUMN "B" SET DATA TYPE text USING "B"::text;--> statement-breakpoint
ALTER TABLE "_media_to_link" ALTER COLUMN "B" SET DATA TYPE text USING "B"::text;--> statement-breakpoint
ALTER TABLE "_media_to_screenshot" ALTER COLUMN "B" SET DATA TYPE text USING "B"::text;--> statement-breakpoint
ALTER TABLE "_media_to_tag" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "_media_to_translation" ALTER COLUMN "B" SET DATA TYPE text USING "B"::text;--> statement-breakpoint
ALTER TABLE "_media_to_video" ALTER COLUMN "B" SET DATA TYPE text USING "B"::text;--> statement-breakpoint
ALTER TABLE "media_translation" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_translation" ALTER COLUMN "iso_639_1" SET DATA TYPE text USING "iso_639_1"::text;--> statement-breakpoint
ALTER TABLE "media_translation" ALTER COLUMN "source" SET DATA TYPE text USING "source"::text;--> statement-breakpoint
ALTER TABLE "media_video" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_video" ALTER COLUMN "type" SET DATA TYPE text USING "type"::text;--> statement-breakpoint
ALTER TABLE "media_video" ALTER COLUMN "source" SET DATA TYPE text USING "source"::text;--> statement-breakpoint
ALTER TABLE "media_voice_actor" ALTER COLUMN "language" SET DATA TYPE text USING "language"::text;--> statement-breakpoint
ALTER TABLE "media_voice_actor" ALTER COLUMN "blood_type" SET DATA TYPE text USING "blood_type"::text;--> statement-breakpoint
ALTER TABLE "media_voice_actor" ALTER COLUMN "gender" SET DATA TYPE text USING "gender"::text;--> statement-breakpoint
ALTER TABLE "media_voice_birth_date" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_voice_death_date" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_voice_image" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "media_voice_name" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "api_key" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "api_key" ALTER COLUMN "key" SET DATA TYPE text USING "key"::text;--> statement-breakpoint
ALTER TABLE "api_key_usage" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "api_key_usage" ALTER COLUMN "api_key_id" SET DATA TYPE text USING "api_key_id"::text;--> statement-breakpoint
ALTER TABLE "api_key_usage" ALTER COLUMN "endpoint" SET DATA TYPE text USING "endpoint"::text;--> statement-breakpoint
ALTER TABLE "api_key_usage" ALTER COLUMN "method" SET DATA TYPE text USING "method"::text;--> statement-breakpoint
ALTER TABLE "api_key_usage" ALTER COLUMN "origin" SET DATA TYPE text USING "origin"::text;--> statement-breakpoint
ALTER TABLE "api_key_usage" ALTER COLUMN "user_agent" SET DATA TYPE text USING "user_agent"::text;--> statement-breakpoint
ALTER TABLE "api_key_usage" ALTER COLUMN "ip" SET DATA TYPE text USING "ip"::text;--> statement-breakpoint
ALTER TABLE "indexer_state" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "tvdb_login" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "update_queue" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;--> statement-breakpoint
ALTER TABLE "zerochan_login" ALTER COLUMN "id" SET DATA TYPE text USING "id"::text;