ALTER TABLE "anime" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_airing_schedule" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_airing_schedule" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_artwork" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_artwork" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_character" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_character" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_character_birth_date" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_character_birth_date" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_character_image" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_character_image" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_character_name" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_character_name" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_chronology" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_chronology" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_end_date" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_end_date" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_episode" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_episode" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_episode_image" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_episode_image" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_genre" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_genre" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_image" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_image" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_link" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_link" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_other_description" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_other_description" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_other_title" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_other_title" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_poster" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_poster" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_recommendation" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_recommendation" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_score_distribution" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_score_distribution" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_screenshot" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_screenshot" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_start_date" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_start_date" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_status_distribution" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_status_distribution" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_studio" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_studio" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_tag" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_tag" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_title" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_title" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_airing_schedule" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_airing_schedule" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_artwork" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_artwork" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_character" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_character" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_genre" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_genre" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_image" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_image" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_link" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_link" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_other_description" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_other_description" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_other_title" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_other_title" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_screenshot" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_screenshot" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_studio" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_studio" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_tag" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_tag" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_video" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "_anime_to_video" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_video" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_video" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_voice_actor" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_voice_actor" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_voice_birth_date" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_voice_birth_date" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_voice_death_date" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_voice_death_date" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_voice_image" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_voice_image" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "anime_voice_name" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "anime_voice_name" ADD COLUMN "updated_at" integer;--> statement-breakpoint
ALTER TABLE "_character_to_voice_actor" ADD COLUMN "created_at" integer;--> statement-breakpoint
ALTER TABLE "_character_to_voice_actor" ADD COLUMN "updated_at" integer;